spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/ai_interview
    username: aimentor
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

integration:
  ai:
    provider: python-ai
    base-url: http://localhost:8000

